/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonballgame;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author polenzani.pietro
 */
public class CharacterSelection extends javax.swing.JFrame {
    GameInteface g = new GameInteface();
    /**
     * Creates new form CharacterSelection
     */
    
    public CharacterSelection() {
        initComponents();
        ImageIcon icon1 = new ImageIcon("immagini/goku_base.png");
        ImageIcon icon2 = new ImageIcon("immagini/gohan_base.png");
        ImageIcon icon3 = new ImageIcon("immagini/vegeta_base.png");      
        btn_character1.setIcon(icon1);    
        btn_character2.setIcon(icon2);
        btn_character3.setIcon(icon3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_character1 = new javax.swing.JButton();
        btn_character2 = new javax.swing.JButton();
        btn_character3 = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_character1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 180));

        btn_character2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 150, 180));

        btn_character3.setToolTipText("");
        btn_character3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 160, 180));

        btn_start.setFont(new java.awt.Font("Stencil", 2, 48)); // NOI18N
        btn_start.setText("START");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 540, 120));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("CHOOSE YOUR CHARACTER ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 670, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_character2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character2ActionPerformed
        Goku goku = new Goku();
        g.setImage("immagini/gohan_base.png");
        g.updateStats(goku);
    }//GEN-LAST:event_btn_character2ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        dispose();
        g.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_character1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character1ActionPerformed
        Goku goku = new Goku();
        g.setImage("immagini/goku_base.png");
        g.updateStats(goku);
    
    }//GEN-LAST:event_btn_character1ActionPerformed

    private void btn_character3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character3ActionPerformed
        Goku goku = new Goku();
        g.setImage("immagini/vegeta_base.png");
        g.updateStats(goku);
    }//GEN-LAST:event_btn_character3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterSelection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_character1;
    private javax.swing.JButton btn_character2;
    private javax.swing.JButton btn_character3;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
