/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonballgame;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author polenzani.pietro
 */
public class CharacterSelection extends javax.swing.JFrame {

    GameInteface g;

    /**
     * Creates new form CharacterSelection
     */

    public CharacterSelection(GameInteface gi) {
        initComponents();
        ImageIcon icon1 = new ImageIcon("immagini/goku_base.png");
        ImageIcon icon2 = new ImageIcon("immagini/gohan_base.png");
        ImageIcon icon3 = new ImageIcon("immagini/vegeta_base.png");
        btn_character1.setIcon(icon1);
        btn_character2.setIcon(icon2);
        btn_character3.setIcon(icon3);
        g = gi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_character1 = new javax.swing.JButton();
        btn_character2 = new javax.swing.JButton();
        btn_character3 = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_character1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 180));

        btn_character2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 150, 180));

        btn_character3.setToolTipText("");
        btn_character3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_character3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_character3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 160, 180));

        btn_start.setFont(new java.awt.Font("Stencil", 2, 48)); // NOI18N
        btn_start.setText("START");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 540, 120));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("CHOOSE YOUR CHARACTER ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 670, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_character2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character2ActionPerformed
        Gohan gohan = new Gohan(80, 70, 85, 0, 80,"immagini/gohan_base.png", "immagini/gohan_beast.png");
        g.setImage(gohan.getImagePath());
        g.setCharacter(gohan);
    }//GEN-LAST:event_btn_character2ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        dispose();
        g.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_character1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character1ActionPerformed
        Goku goku = new Goku(85, 80, 90, 0, 85,"immagini/goku_base.png" , "immagini/goku_mui.png");
        g.setImage(goku.getImagePath());
        g.setCharacter(goku);
    }//GEN-LAST:event_btn_character1ActionPerformed

    private void btn_character3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_character3ActionPerformed
        Vegeta vegeta = new Vegeta(80, 90, 75, 0, 80, "immagini/vegeta_base.png", "immagini/vegeta_ultra_ego.png");
        g.setImage(vegeta.getImagePath());
        g.setCharacter(vegeta);
    }//GEN-LAST:event_btn_character3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_character1;
    private javax.swing.JButton btn_character2;
    private javax.swing.JButton btn_character3;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
