/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonballgame;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author polenzani.pietro
 */
public class GameInteface extends javax.swing.JFrame {
    Player player = new Player();
    GameManager gameManager= new GameManager();
    private String imagePath;
    
    /**
     * Creates new form GameInteface
     */
    public GameInteface() {
        initComponents();
        
    }
    public void setImage(String path) {
    this.imagePath = path;

    ImageIcon icon = new ImageIcon(path);
    Image img = icon.getImage().getScaledInstance(pnl_image.getWidth(),pnl_image.getHeight(),Image.SCALE_SMOOTH);
    JLabel label = new JLabel(new ImageIcon(img));
    pnl_image.add(label);
    pnl_image.revalidate();            
}
    public void updateStats(Character c) {
    lbl_hp.setText(String.valueOf(c.getHp()));
    lbl_stamina.setText(String.valueOf(c.getStamina()));
    lbl_aura.setText(String.valueOf(c.getAura()));
    lbl_att.setText(String.valueOf(c.getAtt()));
}
    public void setUsername(String username) {
    lbl_username.setText(username);
    lbl_username.invalidate();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_hp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_stamina = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_aura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_dragonBalls = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_att = new javax.swing.JLabel();
        btn_nextRound = new javax.swing.JButton();
        pnl_image = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_events = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("hp:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lbl_hp.setText("0");
        jPanel1.add(lbl_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 6, -1, -1));

        jLabel2.setText(" stamina:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        lbl_stamina.setText("0");
        jPanel1.add(lbl_stamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 20, 20));

        jLabel3.setText(" aura");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        lbl_aura.setText("0");
        jPanel1.add(lbl_aura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, -1));

        jLabel4.setText("dragonBalls");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lbl_dragonBalls.setText("0");
        jPanel1.add(lbl_dragonBalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 20, -1));

        jLabel5.setText("att");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        lbl_att.setText("0");
        jPanel1.add(lbl_att, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        btn_nextRound.setText("CONTINUE");
        btn_nextRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextRoundActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nextRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 200, 80));
        getContentPane().add(pnl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, 340));

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_username.setText("USERNAME");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -10, 250, 140));

        txt_events.setColumns(20);
        txt_events.setRows(5);
        jScrollPane1.setViewportView(txt_events);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 280, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextRoundActionPerformed
        gameManager.eventSelection();
        txt_events.setText(EventManager.randomEvent().toString());
    }//GEN-LAST:event_btn_nextRoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInteface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInteface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInteface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInteface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInteface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nextRound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_att;
    private javax.swing.JLabel lbl_aura;
    private javax.swing.JLabel lbl_dragonBalls;
    private javax.swing.JLabel lbl_hp;
    private javax.swing.JLabel lbl_stamina;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_image;
    private javax.swing.JTextArea txt_events;
    // End of variables declaration//GEN-END:variables
}
